---
name: Deploy Docker Image
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0" # at 01.00 week 0 ( every Sunday)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and deploy image
      shell: bash
      env:
        USERNAME: ${{ secrets.GH_USERNAME }}
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        #deploy to ghcr.io
        cd $GITHUB_WORKSPACE
        docker build -t ghcr.io/a2s-institute/gpu-cluster/gpu-cluster-docs:latest .
        docker push ghcr.io/a2s-institute/gpu-cluster/gpu-cluster-docs:latest     

